### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Kevun1** [TheLMiffy1111/EssentialCraft4Unofficial#20]
There seems to be some kind of incompatability with Astral Sorcery. I'm using version 4.8.122.1 on 1.12.2. I was in the overworld in a creative superflat test world when my game suddenly crashed. Here's the log:

java.lang.ClassCastException: hellfirepvp.astralsorcery.common.world.WorldProviderBrightnessInj cannot be cast to essentialcraft.common.world.dim.WorldProviderHoanna
	at essentialcraft.common.world.event.WorldEventDarkness.onEventBeginning(WorldEventDarkness.java:16)
	at essentialcraft.utils.common.ECEventHandler.worldTick(ECEventHandler.java:986)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1002_ECEventHandler_worldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:272)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:774)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

**Comment by TheLMiffy1111** [comment]
dimension id conflict?

**Comment by Kevun1** [comment]
Actually, it seems that Astral Sorcery seems to be hijacking the WorldProvider for other mod's dimensions to do its sky rendering. They said they'll fix it for the next update, so I guess everything's fine from your end.

[Here's the issue.](https://github.com/HellFirePvP/AstralSorcery/issues/271)
