### ISSUE TITLE
Logging issue after placing magic jukebox

### ISSUE THREAD

**Issue by saphsara** [TheLMiffy1111/EssentialCraft4Unofficial#24]
member of server unable to log in after placing jukebox .. game client does not crash ,server does not crash how ever server console keeps stating ...  Not sure what to do ? please advise.

18:55:21] [Server thread/ERROR] [FML]: A TileEntity type net.minecraft.block.BlockJukebox$TileEntityJukebox has throw an exception trying to write state. It will not persist. Report this to the mod author

java.lang.RuntimeException: class net.minecraft.block.BlockJukebox$TileEntityJukebox is missing a mapping! This is a bug!

	at net.minecraft.tileentity.TileEntity.func_189516_d(TileEntity.java:78) ~[avj.class:?]

	at net.minecraft.tileentity.TileEntity.func_189515_b(TileEntity.java:69) ~[avj.class:?]

	at net.minecraft.block.BlockJukebox$TileEntityJukebox.func_189515_b(SourceFile:47) ~[arp$a.class:?]

	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:380) [aye.class:?]

	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:171) [aye.class:?]

	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]

	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]

	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1006) [oo.class:?]

	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]

	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:689) [MinecraftServer.class:?]

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]

	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by TheLMiffy1111** [comment]
will check, what minecraft version?

**Comment by saphsara** [comment]
1.12.2 server
